### ISSUE TITLE
Advice: Clearer and more adjustable parameters.

### ISSUE THREAD

**Issue by win10ogod** [Hannibal046/nanoRWKV#2]
It is recommended to put the adjustable parameters in one block.

**Comment by Hannibal046** [comment]
Hi, thanks for your interest! Could you please elaborate this or show some examples? Thanks

**Comment by win10ogod** [comment]
For example: the parameter that can control the size of the model like (169m,430m)

**Comment by Hannibal046** [comment]
do you mean this? https://github.com/Hannibal046/nanoRWKV/blob/1b57cabde78b059052c729d623bc66118809f889/modeling_rwkv.py#L199-L207

or this? 
https://github.com/Hannibal046/nanoRWKV/blob/1b57cabde78b059052c729d623bc66118809f889/train.py#L155-L160

**Comment by win10ogod** [comment]
Yes, but if we can use clear descriptions, we can let non-relevant practitioners learn more clearly.

**Comment by win10ogod** [comment]
Because the beginner may not want to train too large a model, or may be a rapid prototype iteration.
Note: You can add the function of mixing multiple low parameter models into a composite model.

**Comment by win10ogod** [comment]
Additional idea: you can add the ability to train a back-propagation low-parameter RLHF model mixed with a forward-propagation conventional model as a composite Bi-directional model.

**Comment by Hannibal046** [comment]
Thanks for your advice. But the purpose of this repo is to introduce RWKV while keeping in line with nanoGPT, so the above may be a little bit out of scope.
