### ISSUE TITLE
rwkv训练完成后，不支持推理

### ISSUE THREAD

**Issue by Never-up** [Hannibal046/nanoRWKV#7]
sample.py文件现在还不支持推理吗？好像目前只支持gptt推理

**Comment by Hannibal046** [comment]
你好,支持inference的,参考README里面的Generation

**Comment by Never-up** [comment]
> 你好,支持inference的,参考README里面的Generation

推理是支持，但是不支持rwkv训练之后保存的模型的推理是不支持的。我看过sample.py的代码

**Comment by Hannibal046** [comment]
把这个地方改一下应该就可以,欢迎PR
https://github.com/Hannibal046/nanoRWKV/blob/1d61d49df72f593a030cdd3cb1b4423e68c31d18/sample.py#L36-L47
