### ISSUE TITLE
训练时间似乎比NanoGPT项目的短许多

### ISSUE THREAD

**Issue by Jellyfish042** [Hannibal046/nanoRWKV#9]
我看了日志文件，RWKV 130M和GPT 124M在8X V100上似乎只用了十几个小时就训练完成了。
而[karpathy/nanoGPT](https://github.com/karpathy/nanoGPT)中提到在复现GPT-2 124M时他使用了8X A100训练了4天才达到和本项目相同的Loss。
我想知道这是什么原因，还是说我的理解错误了？

**Comment by Hannibal046** [comment]
没有呀,公开的wanbd log是在8*v100 训练的,时间更长

![image](https://github.com/Hannibal046/nanoRWKV/assets/38466901/f9533d80-da5e-4e7e-bd3b-f0f06b5b7842)
